-- Publishing the assessment, and the interim report.
--
-- Confirming an assessment settles what the school found. Publishing decides
-- that the public may read it — two different acts, both the principal's, and
-- until now the second did not exist: any confirmed cycle was public.
--
-- The backfill at the end matters. Six schools already had confirmed cycles
-- showing on the public tier, and adding the gate without it would have
-- silently taken them down. They are marked published, which is what they
-- effectively were; every cycle confirmed from now on needs the school to say
-- so.
--
-- Generated by `prisma migrate diff`, plus that backfill. Additive throughout:
-- no index is dropped, so nothing here can trip over a foreign key the way the
-- rating-tracks migration did.

-- AlterTable
ALTER TABLE `AssessmentCycle` ADD COLUMN `publishedAt` DATETIME(3) NULL,
    ADD COLUMN `publishedById` INTEGER NULL;

-- CreateTable
CREATE TABLE `PlanReport` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `planId` INTEGER NOT NULL,
    `kind` VARCHAR(191) NOT NULL,
    `narrative` TEXT NULL,
    `snapshot` JSON NULL,
    `publishedAt` DATETIME(3) NULL,
    `publishedById` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `PlanReport_planId_kind_key`(`planId`, `kind`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AssessmentCycle` ADD CONSTRAINT `AssessmentCycle_publishedById_fkey` FOREIGN KEY (`publishedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlanReport` ADD CONSTRAINT `PlanReport_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `DevelopmentPlan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlanReport` ADD CONSTRAINT `PlanReport_publishedById_fkey` FOREIGN KEY (`publishedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;


-- Preserve what the public could already see: a cycle that was confirmed before
-- publication existed was, in practice, published.
UPDATE `AssessmentCycle`
   SET `publishedAt` = COALESCE(`confirmedAt`, NOW())
 WHERE `status` = 'CONFIRMED' AND `publishedAt` IS NULL;
