-- The DigiPlan gains intents, initiatives and KPIs.
--
-- Every parameter is now a row in the plan, with an intent of ADVANCE or
-- MAINTAIN, rather than the plan being a shortlist of up to five priorities.
-- A school advancing three parameters is also committing to hold sixteen where
-- they are, and holding a level is work with requirements of its own.
--
-- `rationale` and `actions` become nullable: the work now lives in initiatives,
-- and the plan opens with all nineteen rows before anyone has written anything.
-- Safe to relax here because no plan exists yet in any environment.
--
-- Generated by `prisma migrate diff` and kept as generated: this change only
-- adds tables, columns and constraints. The last migration had to be written by
-- hand because it dropped an index a foreign key was using — nothing here
-- drops anything.

-- AlterTable
ALTER TABLE `DevelopmentPlan` ADD COLUMN `endsOn` DATETIME(3) NULL,
    ADD COLUMN `startsOn` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `PlanPriority` ADD COLUMN `intent` VARCHAR(191) NOT NULL DEFAULT 'MAINTAIN',
    MODIFY `rationale` TEXT NULL,
    MODIFY `actions` TEXT NULL;

-- CreateTable
CREATE TABLE `PlanInitiative` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `priorityId` INTEGER NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `responsibleUserId` INTEGER NULL,
    `responsibleName` VARCHAR(191) NULL,
    `supervisorUserId` INTEGER NULL,
    `supervisorName` VARCHAR(191) NULL,
    `startsOn` DATETIME(3) NULL,
    `dueOn` DATETIME(3) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'NOT_STARTED',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `PlanInitiative_priorityId_idx`(`priorityId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PlanKpi` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `initiativeId` INTEGER NOT NULL,
    `measure` VARCHAR(191) NOT NULL,
    `target` VARCHAR(191) NOT NULL,
    `actual` VARCHAR(191) NULL,

    INDEX `PlanKpi_initiativeId_idx`(`initiativeId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE UNIQUE INDEX `PlanPriority_planId_indicatorCode_key` ON `PlanPriority`(`planId`, `indicatorCode`);

-- AddForeignKey
ALTER TABLE `PlanInitiative` ADD CONSTRAINT `PlanInitiative_priorityId_fkey` FOREIGN KEY (`priorityId`) REFERENCES `PlanPriority`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlanInitiative` ADD CONSTRAINT `PlanInitiative_responsibleUserId_fkey` FOREIGN KEY (`responsibleUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlanInitiative` ADD CONSTRAINT `PlanInitiative_supervisorUserId_fkey` FOREIGN KEY (`supervisorUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlanKpi` ADD CONSTRAINT `PlanKpi_initiativeId_fkey` FOREIGN KEY (`initiativeId`) REFERENCES `PlanInitiative`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

